---
version: "3.1"
services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=New_York/America
    volumes:
      - /mnt/D_Drive/grocy/config:/config
    ports:
      - 9283:80
    restart: unless-stopped
